language: node_js
notifications:
  email: false
  slack:
    secure: WPmKf7xFXCGgY7Ssmp3/eyKhaCICQO1KGy37BSUyg+EVFXqzd4n3ImDgwNK05x9BNyzCKyj8fcgMtPfiWjKIzwDlqk+VlQAhktKfY6zfkSbRKoUWJMUUeJcQ+o8bv6769px09pYHlnXjeJLx8jhRZInU9sWfU+HZnIoF2j7zbfItb4jBUWCCzyASbAkWRScPky+iM4I76VZpyDglSGqsePeNR3w1D0InWe2hQ4XPJmrot3vdA92HSRbYdDyyr6u4lkU/xmZjs+k97souIifrT2yyRudHmZCVzuc1bCHexM0cLO4p9/SgIp+TFnjQwIbmLMr91JDMoUwC9Pth0WnzUU2bs8/X3gN5+pAH0vip9nEn3jCD3RP01CIVeS/A/U82exU1v1cy5xSS0AkDg9ubXk+qBx2MGrXHwCGrIb7fH28ArX8qXpRNfleL44JVjbHwwbKE3OOWzlgpnEFKctEBpMxcd6wy1N/V9NMh+w1hBTlpHtDguqn9VrJPOxKULgbKcV5QPQIAj+wHq+a+F7+FMf7kLJHOeK0/2de83fnTOMIERetZDs44D0O/TLAlUsN13LvomqiQfvR6kup8bdzeu55XgUs/I3GVB3k/p5eRerPzEwywnv2dC0QneL6dYuRXHQ+86DdysEQQawzKiS22s5s1vGsARt/IZ/EyO2fsd0Q=
node_js:
- '7'
before_script:
- npm prune
script:
- xmllint tikatuka.svg --noout
after_success:
- curl -Lo travis_after_all.py https://git.io/travis_after_all
- python travis_after_all.py
- export $(cat .to_export_back) &> /dev/null
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/